language: node_js
os:
  - linux
node_js:
  - "6"
env:
  - export CONTINUOUS_INTEGRATION=1
before_install:
  - node --version
  - npm --version
script:
  - npm run eslint
  - npm test
  - npm run build
